FROM node:20-alpine AS base

RUN apk add --no-cache libc6-compat

WORKDIR /app

FROM base AS deps

COPY package.json package-lock.json* ./

RUN if [ -f package-lock.json ]; then npm ci --legacy-peer-deps; \
    else echo "Lockfile not found." && exit 1; \
    fi

FROM base AS builder

ARG GIT_TAG
ARG DATABASE_URL
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG NODE_ENV=production
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG EMAIL_USER
ARG RESEND_API_KEY
ARG WHATSAPP_API_KEY
ARG WHATSAPP_API_URL
ARG WHATSAPP_ADMIN_NUMBERS
ARG WHATSAPP_ENABLED

# Set environment variables from build args
ENV DATABASE_URL=${DATABASE_URL}
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
ENV BETTER_AUTH_URL=${BETTER_AUTH_URL}
ENV NODE_ENV=${NODE_ENV}
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
ENV NEXT_PUBLIC_CLOUDINARY_API_KEY=${NEXT_PUBLIC_CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV EMAIL_USER=${EMAIL_USER}
ENV RESEND_API_KEY=${RESEND_API_KEY}
ENV WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
ENV WHATSAPP_API_URL=${WHATSAPP_API_URL}
ENV WHATSAPP_ADMIN_NUMBERS=${WHATSAPP_ADMIN_NUMBERS}
ENV WHATSAPP_ENABLED=${WHATSAPP_ENABLED}
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

RUN npm run build

FROM base AS runner

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

RUN mkdir -p /app/.next/static && chown -R nextjs:nodejs /app

# Switch to non-root user
USER nextjs

# Pass public environment variables and runtime configuration
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_CLOUDINARY_API_KEY
ARG NODE_ENV=production
ARG GIT_TAG
ARG DATABASE_URL
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG EMAIL_USER
ARG RESEND_API_KEY
ARG WHATSAPP_API_KEY
ARG WHATSAPP_API_URL
ARG WHATSAPP_ADMIN_NUMBERS
ARG WHATSAPP_ENABLED
ARG CLOUDINARY_API_SECRET

# Set runtime environment variables
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
ENV NEXT_PUBLIC_CLOUDINARY_API_KEY=${NEXT_PUBLIC_CLOUDINARY_API_KEY}
ENV NODE_ENV=${NODE_ENV}
ENV DATABASE_URL=${DATABASE_URL}
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
ENV BETTER_AUTH_URL=${BETTER_AUTH_URL}
ENV EMAIL_USER=${EMAIL_USER}
ENV RESEND_API_KEY=${RESEND_API_KEY}
ENV WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
ENV WHATSAPP_API_URL=${WHATSAPP_API_URL}
ENV WHATSAPP_ADMIN_NUMBERS=${WHATSAPP_ADMIN_NUMBERS}
ENV WHATSAPP_ENABLED=${WHATSAPP_ENABLED}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV PORT=3223
ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

COPY --from=builder --chown=nextjs:nodejs /app/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

EXPOSE 3223

CMD ["node", "server.js"]

LABEL git.tag=${GIT_TAG}