export const KECAMATAN_LIST = [
  'Amandraya',
  'Aramo',
  'Boronadu',
  'Fanayama',
  'Gomo',
  'Hibala',
  'Hilimegai',
  'Hilisalawaahe',
  'Huruna',
  'Idanotae',
  'Lahusa',
  'Lolomatua',
  'Lolowau',
  'Luahagundre Maniamolo',
  'Maniamolo',
  'Mazino',
  'Mazo',
  'Onohazumba',
  'Onolalu',
  'Oou',
  'Pulau-Pulau Batu',
  'Pulau-Pulau Batu Barat',
  'Pulau-Pulau Batu Timur',
  'Pulau-Pulau Batu Utara',
  'Siduaori',
  'Simuk',
  'Somambawa',
  'Susua',
  'Tanah Masa',
  'Teluk Dalam',
  'Toma',
  'Ulu Idanotae',
  'Ulunoyo',
  'Ulususua',
  'Umbunasi',
] as const;

export type Kecamatan = (typeof KECAMATAN_LIST)[number];
